name: 'Dependadoc'
description: 'Mirror documentation files to another repo'
inputs:
  mirrored-folder:
    description: 'folder to evaluate for changed files'
    required: true
  docs-repository:
    description: 'repo to open PR against, e.g., yourorg/your-repo'
    required: true
  docs-repository-path:
    description: 'relative path to place mirrored folder'
    required: false
    default: '.'
  docs-repository-token-variable:
    description: 'name of variable where repo token is stored; default is DOC_REPO_TOKEN'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout $GITHUB_REPOSITORY
      uses: actions/checkout@v3 
      with:
        path: main
    - name: Checkout ${{ inputs.docs-repository }}
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.docs-repository }}
        path: docs
        token: ${{ inputs.docs-repository-token-variable }}
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: dependadoc.sh
      shell: bash
      working-directory: $GITHUB_WORKSPACE/docs
      env:
        MIRRORED_FOLDER: ${{ inputs.mirrored-folder }}
        MIRRORED_REPOSITORY_FULL_NAME: $GITHUB_REPOSITORY
        DOCS_REPOSITORY_PATH: ${{ inputs.docs-repository-path}}
        GITHUB_ACTOR: $GITHUB_ACTOR
        GITHUB_WORKSPACE: $GITHUB_WORKSPACE
